In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('handsets_opendata_fixed.csv')

In [3]:
data.head()

,CAL_DT,MODEL_NAME,BRAND_FULL_NAME,BRAND_NAME,VENDOR_NAME,OS_NAME,DEVICE_TYPE,_2G_FLG,_3G_FLG,_4G_FLG,WIFI_FLG,BLUETOOTH_FLG,TOUCH_SCREEN_FLG,DUAL_SIM_FLG,GENDER_TYPE_CD,AGE_B,NATIONALITY_CD,NATIONALITY_NAME,SAUDI_NON_SAUDI,DEVICE_COUNT
0,1/31/2019,One x9,HTC One x9,HTC,Google,Android,Smartphone,Y,Y,Y,Y,Y,Y,Y,Male,36-55,LKA,Sri Lanka,Non-Saudi,9
1,5/31/2020,X2-00,Nokia X2-00,Nokia,Nokia,Proprietary,Mobile Phone,Y,N,N,N,Y,N,N,Male,<18,NaN,NaN,Non-Saudi,1
2,1/31/2019,Desire 626 NFC Dual Sim,HTC Desire 626 NFC Dual Sim,HTC,Google,Android,Smartphone,Y,Y,Y,Y,Y,Y,Y,NaN,26-35,SAU,Saudi Arabia,Saudi,1
3,12/31/2019,C7-00,Nokia C7-00,Nokia,Nokia,Symbian,Smartphone,Y,Y,N,Y,Y,Y,N,Male,18-25,BGD,Bangladesh,Non-Saudi,2
4,9/30/2019,1202,Nokia 1202,Nokia,Nokia,Proprietary,Mobile Phone,Y,N,N,N,N,N,N,NaN,36-55,BGD,Bangladesh,Non-Saudi,4

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3150708 entries, 0 to 3150707
Data columns (total 20 columns):
 #   Column            Dtype
---  ------            -----
 0   CAL_DT            object
 1   MODEL_NAME        object
 2   BRAND_FULL_NAME   object
 3   BRAND_NAME        object
 4   VENDOR_NAME       object
 5   OS_NAME           object
 6   DEVICE_TYPE       object
 7   _2G_FLG           object
 8   _3G_FLG           object
 9   _4G_FLG           object
 10  WIFI_FLG          object
 11  BLUETOOTH_FLG     object
 12  TOUCH_SCREEN_FLG  object
 13  DUAL_SIM_FLG      object
 14  GENDER_TYPE_CD    object
 15  AGE_B             object
 16  NATIONALITY_CD    object
 17  NATIONALITY_NAME  object
 18  SAUDI_NON_SAUDI   object
 19  DEVICE_COUNT      int64
dtypes: int64(1), object(19)
memory usage: 480.8+ MB

# Data Preprocessing

In [8]:
data.BRAND_NAME.value_counts()

BRAND_NAME
Nokia      993403
Lenovo     206445
HTC        190184
Sony       163946
Xiaomi     162901
            ...
Hiro            3
Siemens         2
Gee Pee         2
I KALL          1
Malata          1
Name: count, Length: 227, dtype: int64