In [1]:
import pandas as pd

In [4]:
data = pd.read_csv('handsets_opendata_fixed.csv')
data.head(10)

,CAL_DT,MODEL_NAME,BRAND_FULL_NAME,BRAND_NAME,VENDOR_NAME,OS_NAME,DEVICE_TYPE,_2G_FLG,_3G_FLG,_4G_FLG,WIFI_FLG,BLUETOOTH_FLG,TOUCH_SCREEN_FLG,DUAL_SIM_FLG,GENDER_TYPE_CD,AGE_B,NATIONALITY_CD,NATIONALITY_NAME,SAUDI_NON_SAUDI,DEVICE_COUNT
0,1/31/2019,One x9,HTC One x9,HTC,Google,Android,Smartphone,Y,Y,Y,Y,Y,Y,Y,Male,36-55,LKA,Sri Lanka,Non-Saudi,9
1,5/31/2020,X2-00,Nokia X2-00,Nokia,Nokia,Proprietary,Mobile Phone,Y,N,N,N,Y,N,N,Male,<18,NaN,NaN,Non-Saudi,1
2,1/31/2019,Desire 626 NFC Dual Sim,HTC Desire 626 NFC Dual Sim,HTC,Google,Android,Smartphone,Y,Y,Y,Y,Y,Y,Y,NaN,26-35,SAU,Saudi Arabia,Saudi,1
3,12/31/2019,C7-00,Nokia C7-00,Nokia,Nokia,Symbian,Smartphone,Y,Y,N,Y,Y,Y,N,Male,18-25,BGD,Bangladesh,Non-Saudi,2
4,9/30/2019,1202,Nokia 1202,Nokia,Nokia,Proprietary,Mobile Phone,Y,N,N,N,N,N,N,NaN,36-55,BGD,Bangladesh,Non-Saudi,4
5,4/30/2020,Blade V7 Lite,ZTE Blade V7 Lite,ZTE,Google,Android,Smartphone,Y,Y,Y,Y,Y,Y,Y,Female,>55,IDN,Indonesia,Non-Saudi,1
6,8/31/2019,i6 Metal ONE,QMobile i6 Metal ONE,QMobile,Google,Android,Smartphone,Y,Y,N,Y,Y,Y,Y,Male,36-55,EGY,Egypt,Non-Saudi,1
7,1/31/2020,SHF33,au SHF33,au,Google,Android,Smartphone,Y,Y,Y,Y,Y,Y,N,NaN,NA,SAU,Saudi Arabia,Saudi,1
8,6/30/2019,One M9,HTC One M9,HTC,Google,Android,Smartphone,Y,Y,Y,Y,Y,Y,N,Male,26-35,SYR,Syria,Non-Saudi,21
9,6/30/2020,ScanPal EDA50,Honeywell ScanPal EDA50,Honeywell,Google,Android,Smartphone,Y,Y,Y,Y,Y,Y,N,Male,36-55,SAU,Saudi Arabia,Saudi,91

In [6]:
data.drop(columns=['SAUDI_NON_SAUDI', 'BRAND_NAME'], inplace=True)

In [7]:
data.tail(10)

,CAL_DT,MODEL_NAME,BRAND_FULL_NAME,VENDOR_NAME,OS_NAME,DEVICE_TYPE,_2G_FLG,_3G_FLG,_4G_FLG,WIFI_FLG,BLUETOOTH_FLG,TOUCH_SCREEN_FLG,DUAL_SIM_FLG,GENDER_TYPE_CD,AGE_B,NATIONALITY_CD,NATIONALITY_NAME,DEVICE_COUNT
3150698,9/30/2019,A2010 Dual Sim,Lenovo A2010 Dual Sim,Google,Android,Smartphone,Y,Y,Y,Y,Y,Y,Y,Male,NA,EGY,Egypt,12
3150699,9/30/2019,A2010 Dual Sim,Lenovo A2010 Dual Sim,Google,Android,Smartphone,Y,Y,Y,Y,Y,Y,Y,NaN,36-55,EGY,Egypt,2
3150700,9/30/2019,A2010 Dual Sim,Lenovo A2010 Dual Sim,Google,Android,Smartphone,Y,Y,Y,Y,Y,Y,Y,Male,NA,IND,India,88
3150701,9/30/2019,A2010 Dual Sim,Lenovo A2010 Dual Sim,Google,Android,Smartphone,Y,Y,Y,Y,Y,Y,Y,Male,26-35,SYR,Syria,6
3150702,9/30/2019,A2010 Dual Sim,Lenovo A2010 Dual Sim,Google,Android,Smartphone,Y,Y,Y,Y,Y,Y,Y,Female,>55,PHL,Philippines,4
3150703,9/30/2019,A2010 Dual Sim,Lenovo A2010 Dual Sim,Google,Android,Smartphone,Y,Y,Y,Y,Y,Y,Y,Female,>55,LBY,Libya,1
3150704,9/30/2019,A2010 Dual Sim,Lenovo A2010 Dual Sim,Google,Android,Smartphone,Y,Y,Y,Y,Y,Y,Y,Male,26-35,JOR,Jordan,2
3150705,9/30/2019,A2010 Dual Sim,Lenovo A2010 Dual Sim,Google,Android,Smartphone,Y,Y,Y,Y,Y,Y,Y,Male,NA,NPL,Nepal,6
3150706,9/30/2019,A2010 Dual Sim,Lenovo A2010 Dual Sim,Google,Android,Smartphone,Y,Y,Y,Y,Y,Y,Y,Male,>55,KWT,Kuwait,1
3150707,9/30/2019,A2010 Dual Sim,Lenovo A2010 Dual Sim,Google,Android,Smartphone,Y,Y,Y,Y,Y,Y,Y,Male,26-35,EGY,Egypt,49

In [8]:
data.TOUCH_SCREEN_FLG.value_counts()

TOUCH_SCREEN_FLG
Y    1965028
N    1171405
Z      14275
Name: count, dtype: int64

In [10]:
data.head(20)

,CAL_DT,MODEL_NAME,BRAND_FULL_NAME,VENDOR_NAME,OS_NAME,DEVICE_TYPE,_2G_FLG,_3G_FLG,_4G_FLG,WIFI_FLG,BLUETOOTH_FLG,TOUCH_SCREEN_FLG,DUAL_SIM_FLG,GENDER_TYPE_CD,AGE_B,NATIONALITY_CD,NATIONALITY_NAME,DEVICE_COUNT
0,1/31/2019,One x9,HTC One x9,Google,Android,Smartphone,Y,Y,Y,Y,Y,Y,Y,Male,36-55,LKA,Sri Lanka,9
1,5/31/2020,X2-00,Nokia X2-00,Nokia,Proprietary,Mobile Phone,Y,N,N,N,Y,N,N,Male,<18,NaN,NaN,1
2,1/31/2019,Desire 626 NFC Dual Sim,HTC Desire 626 NFC Dual Sim,Google,Android,Smartphone,Y,Y,Y,Y,Y,Y,Y,NaN,26-35,SAU,Saudi Arabia,1
3,12/31/2019,C7-00,Nokia C7-00,Nokia,Symbian,Smartphone,Y,Y,N,Y,Y,Y,N,Male,18-25,BGD,Bangladesh,2
4,9/30/2019,1202,Nokia 1202,Nokia,Proprietary,Mobile Phone,Y,N,N,N,N,N,N,NaN,36-55,BGD,Bangladesh,4
5,4/30/2020,Blade V7 Lite,ZTE Blade V7 Lite,Google,Android,Smartphone,Y,Y,Y,Y,Y,Y,Y,Female,>55,IDN,Indonesia,1
6,8/31/2019,i6 Metal ONE,QMobile i6 Metal ONE,Google,Android,Smartphone,Y,Y,N,Y,Y,Y,Y,Male,36-55,EGY,Egypt,1
7,1/31/2020,SHF33,au SHF33,Google,Android,Smartphone,Y,Y,Y,Y,Y,Y,N,NaN,NA,SAU,Saudi Arabia,1
8,6/30/2019,One M9,HTC One M9,Google,Android,Smartphone,Y,Y,Y,Y,Y,Y,N,Male,26-35,SYR,Syria,21
9,6/30/2020,ScanPal EDA50,Honeywell ScanPal EDA50,Google,Android,Smartphone,Y,Y,Y,Y,Y,Y,N,Male,36-55,SAU,Saudi Arabia,91
10,7/31/2020,Freddy Dual Sim,Wiko Freddy Dual Sim,Google,Android,Smartphone,Y,Y,Y,Y,Y,Y,Y,Female,36-55,SAU,Saudi Arabia,3
11,5/31/2020,Xperia L,Sony Xperia L,Google,Android,Smartphone,Y,Y,N,Y,Y,Y,N,Male,>55,SYR,Syria,1
12,9/30/2020,101,Nokia 101,Nokia,Proprietary,Mobile Phone,Y,N,N,N,N,N,Y,Female,26-35,MRT,Mauritania,1
13,6/30/2020,E66,Nokia E66,Symbian LTD,Symbian,Smartphone,Y,Y,N,Y,Y,N,N,Male,NA,NaN,NaN,3
14,1/31/2020,Asha 311,Nokia Asha 311,Nokia,Proprietary,Mobile Phone,Y,Y,N,Y,Y,Y,N,Female,>55,SDN,Sudan,1
15,9/30/2020,E51,Nokia E51,Symbian LTD,Symbian,Mobile Phone,Y,Y,N,Y,Y,N,N,Male,NA,IND,India,15
16,7/31/2019,Tribute HD,LG Tribute HD,Google,Android,Smartphone,Y,Y,Y,Y,Y,Y,N,Male,>55,BGD,Bangladesh,1
17,5/31/2020,Y69,Vivo Y69,Google,Android,Smartphone,Y,Y,Y,Y,Y,Y,Y,Female,26-35,PAK,Pakistan,1
18,10/31/2019,ZenFone Live ZB501KL Dual Sim,ASUS ZenFone Live ZB501KL Dual Sim,Google,Android,Smartphone,Y,Y,Y,Y,Y,Y,Y,Male,18-25,SAU,Saudi Arabia,11
19,9/30/2019,Xperia XA1 Dual Sim,Sony Xperia XA1 Dual Sim,Google,Android,Smartphone,Y,Y,Y,Y,Y,Y,Y,Female,36-55,IDN,Indonesia,4

In [12]:
import pandas as pd
import random
import numpy as np

def unclean_dataset(df, corruption_rate=0.3, seed=42):
    random.seed(seed)
    np.random.seed(seed)
    
    def dirty_date(date_str):
        try:
            if random.random() < 0.5:
                return date_str.replace('/', '-')  # e.g., 1-31-2019
            elif random.random() < 0.5:
                return date_str[::-1]  # reverse string
            else:
                return '2019/9/3O'  # typo example
        except:
            return date_str

    def dirty_text(text):
        if pd.isna(text): return text
        text = str(text)
        if random.random() < 0.5:
            text = text.lower()
        if random.random() < 0.3:
            text = text.replace('o', '0').replace('O', '0')
        if random.random() < 0.3:
            text = text.replace('i', '1').replace('e', '3')
        if random.random() < 0.3:
            text += random.choice(['!', '@', '...', '?'])
        return text

    def dirty_flag(flag):
        if flag not in ['Y', 'N', 'y', 'n']: return flag
        return random.choice(['Y', 'N', '1', '0', 'yes', 'no', '-', '??', 'n/a'])

    def dirty_gender(g):
        return random.choice(['M', 'F', 'm/f', 'unknown', g, np.nan])

    def dirty_age(age):
        return random.choice(['unkwn', '<18', '>55', 'twenty', '36–55', age, np.nan])

    def dirty_country_code(code):
        return str(code).lower().replace('u', 'v').replace('a', '@') + random.choice(['', '?'])

    def dirty_country_name(name):
        return str(name).lower().replace(' ', '') + random.choice(['??', '...', '', '!!'])

    def dirty_device_count(val):
        if random.random() < 0.3:
            return random.choice(['one', 'five', 'twelve units', 'NaN', np.nan])
        return val

    df_dirty = df.copy()
    for idx, row in df_dirty.iterrows():
        for col in df_dirty.columns:
            if random.random() > corruption_rate:
                continue  # Skip corruption on this field

            if col == 'CAL_DT':
                df_dirty.at[idx, col] = dirty_date(row[col])
            elif col in ['MODEL_NAME', 'BRAND_FULL_NAME', 'VENDOR_NAME', 'OS_NAME', 'DEVICE_TYPE']:
                df_dirty.at[idx, col] = dirty_text(row[col])
            elif col.endswith('_FLG') and col != 'DUAL_SIM_FLG':
                df_dirty.at[idx, col] = dirty_flag(row[col])
            elif col == 'GENDER_TYPE_CD':
                df_dirty.at[idx, col] = dirty_gender(row[col])
            elif col == 'AGE_B':
                df_dirty.at[idx, col] = dirty_age(row[col])
            elif col == 'NATIONALITY_CD':
                df_dirty.at[idx, col] = dirty_country_code(row[col])
            elif col == 'NATIONALITY_NAME':
                df_dirty.at[idx, col] = dirty_country_name(row[col])
            elif col == 'DEVICE_COUNT':
                df_dirty.at[idx, col] = dirty_device_count(row[col])
            # DUAL_SIM_FLG remains clean

    return df_dirty

In [13]:
df = unclean_dataset(data, corruption_rate=0.3, seed=42)

/var/folders/0z/nh4zphkd0ljgxbl85xr8nlp00000gn/T/ipykernel_24184/2525028176.py:75: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'NaN' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_dirty.at[idx, col] = dirty_device_count(row[col])

In [14]:
df.head()

,CAL_DT,MODEL_NAME,BRAND_FULL_NAME,VENDOR_NAME,OS_NAME,DEVICE_TYPE,_2G_FLG,_3G_FLG,_4G_FLG,WIFI_FLG,BLUETOOTH_FLG,TOUCH_SCREEN_FLG,DUAL_SIM_FLG,GENDER_TYPE_CD,AGE_B,NATIONALITY_CD,NATIONALITY_NAME,DEVICE_COUNT
0,1/31/2019,0ne x9,HTC One x9,g00gl3,android...,Smartphone,1,Y,Y,no,-,no,Y,Male,36-55,LKA,Sri Lanka,9
1,5/31/2020,X2-00,Nokia X2-00,Nokia,Proprietary,Mobile Phone,0,N,N,N,Y,N,N,Male,>55,n@n?,NaN,1
2,2019/9/3O,desire 626 nfc dual sim,htc d3s1r3 626 nfc dual s1m,Google,Android,Smartphone?,Y,Y,Y,0,Y,Y,Y,NaN,26-35,SAU,Saudi Arabia,1
3,12/31/2019,C7-00,nokia c7-00,Nokia,Symbian,Smartphone...,Y,Y,1,Y,Y,Y,N,Male,unkwn,BGD,bangladesh...,2
4,9/30/2019,1202,Nokia 1202,n0kia,Proprietary,Mobile Phone,N,??,N,N,N,??,N,NaN,36-55,BGD,bangladesh...,4

In [22]:
import pandas as pd
import random
import numpy as np
import re

def reversible_noise(text, strength=0.3):
    """
    Add reversible noise to string:
    - Randomly change case
    - Insert symbols like '.', ',', '-', '_', '@', '#', '$', '%'
    - Insert random spaces
    """
    if pd.isna(text):
        return text
    text = str(text)
    noisy = ""
    for c in text:
        r = random.random()
        if r < strength / 2:
            # Random case change
            c = c.upper() if random.random() < 0.5 else c.lower()
            noisy += c
        elif r < strength:
            # Append random symbol after character
            noisy += c + random.choice(['.', ',', '_', '@', '#', '$', '%', ' '])
        else:
            noisy += c
    return noisy

def reversible_dirty_dataset(df, corruption_rate=0.4, strength=0.3, seed=42):
    random.seed(seed)
    np.random.seed(seed)

    df_dirty = df.copy()

    for idx, row in df_dirty.iterrows():
        for col in df_dirty.columns:
            if col == 'DUAL_SIM_FLG':
                continue  # keep original, no noise here

            if random.random() > corruption_rate:
                continue  # skip some fields for partial corruption

            val = row[col]
            # Only dirty strings or numbers (convert numbers to str)
            if isinstance(val, (str, int, float)):
                dirty_val = reversible_noise(val, strength=strength)
                df_dirty.at[idx, col] = dirty_val

    return df_dirty

def simple_clean_string(text):
    """
    Clean the reversible noise by:
    - Removing all symbols except letters, digits, and spaces
    - Lowercasing
    - Stripping spaces
    """
    if pd.isna(text):
        return text
    text = str(text)
    text = re.sub(r'[^A-Za-z0-9\s]', '', text)
    text = re.sub(r'\s+', ' ', text)  # collapse multiple spaces
    return text.strip().lower()

def clean_reversible_dataset(df_dirty, columns=None):
    df_cleaned = df_dirty.copy()
    cols = columns if columns else df_dirty.columns

    for col in cols:
        if col == 'DUAL_SIM_FLG':
            continue  # keep original as is
        df_cleaned[col] = df_cleaned[col].apply(simple_clean_string)

    return df_cleaned

# Example usage:
if __name__ == "__main__":
    # Load your clean dataset (replace with your actual file)
    

    # Apply reversible noise
    df_dirty = reversible_dirty_dataset(df, corruption_rate=0.5, strength=0.4)


    print("Done! Dirty and restored datasets created.")

/var/folders/0z/nh4zphkd0ljgxbl85xr8nlp00000gn/T/ipykernel_24184/2697356928.py:48: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_dirty.at[idx, col] = dirty_val

Done! Dirty and restored datasets created.

In [24]:
df_dirty.head()

,CAL_DT,MODEL_NAME,BRAND_FULL_NAME,VENDOR_NAME,OS_NAME,DEVICE_TYPE,_2G_FLG,_3G_FLG,_4G_FLG,WIFI_FLG,BLUETOOTH_FLG,TOUCH_SCREEN_FLG,DUAL_SIM_FLG,GENDER_TYPE_CD,AGE_B,NATIONALITY_CD,NATIONALITY_NAME,DEVICE_COUNT
0,2019-01-31,O@Ne x9,HTC One. X9@,Google,Android,"SmartpHo,ne",Y,Y,Y#,Y,Y,Y,Y,Male,36@-55,LK@A,Sri Lanka,9
1,2020-05-31_,X2-00,NokiA X2-00,Nokia,PRopri_etarY,MobilE Ph@onE,Y,N,N,N,Y,N@,N,Male,<1 8 @,NaN,NaN,1
2,20 1_9-01 -31,"DesiRe, @626 nFc Dua%l %SIm",HTC DEsIRe 626 NFC Dual# $S%im,Google,Android,SmarTPh one,Y,Y,Y,Y,Y,Y,Y,NaN,26-#35.,SA.U_,Saudi Arabia,1
3,2019-12-31,C7-00,Nokia C7-00,Nokia,"S,y%mbia_n",Smartphone,Y,Y,N,Y,Y,Y,N,Male,18-@2#5,BGD,"Ba$ngla,de$sh",2
4,2019-09-30,1202,Noki#a 1_20.2@,Nokia,Proprietary,Mobile Phone,Y,N,N,N,N,N@,N,NaN,36-55,BGD,Bangladesh,4_

In [26]:
data = pd.read_csv('handsets_opendata_fixed.csv')
data.head(10)

,CAL_DT,MODEL_NAME,BRAND_FULL_NAME,BRAND_NAME,VENDOR_NAME,OS_NAME,DEVICE_TYPE,_2G_FLG,_3G_FLG,_4G_FLG,WIFI_FLG,BLUETOOTH_FLG,TOUCH_SCREEN_FLG,DUAL_SIM_FLG,GENDER_TYPE_CD,AGE_B,NATIONALITY_CD,NATIONALITY_NAME,SAUDI_NON_SAUDI,DEVICE_COUNT
0,1/31/2019,One x9,HTC One x9,HTC,Google,Android,Smartphone,Y,Y,Y,Y,Y,Y,Y,Male,36-55,LKA,Sri Lanka,Non-Saudi,9
1,5/31/2020,X2-00,Nokia X2-00,Nokia,Nokia,Proprietary,Mobile Phone,Y,N,N,N,Y,N,N,Male,<18,NaN,NaN,Non-Saudi,1
2,1/31/2019,Desire 626 NFC Dual Sim,HTC Desire 626 NFC Dual Sim,HTC,Google,Android,Smartphone,Y,Y,Y,Y,Y,Y,Y,NaN,26-35,SAU,Saudi Arabia,Saudi,1
3,12/31/2019,C7-00,Nokia C7-00,Nokia,Nokia,Symbian,Smartphone,Y,Y,N,Y,Y,Y,N,Male,18-25,BGD,Bangladesh,Non-Saudi,2
4,9/30/2019,1202,Nokia 1202,Nokia,Nokia,Proprietary,Mobile Phone,Y,N,N,N,N,N,N,NaN,36-55,BGD,Bangladesh,Non-Saudi,4
5,4/30/2020,Blade V7 Lite,ZTE Blade V7 Lite,ZTE,Google,Android,Smartphone,Y,Y,Y,Y,Y,Y,Y,Female,>55,IDN,Indonesia,Non-Saudi,1
6,8/31/2019,i6 Metal ONE,QMobile i6 Metal ONE,QMobile,Google,Android,Smartphone,Y,Y,N,Y,Y,Y,Y,Male,36-55,EGY,Egypt,Non-Saudi,1
7,1/31/2020,SHF33,au SHF33,au,Google,Android,Smartphone,Y,Y,Y,Y,Y,Y,N,NaN,NA,SAU,Saudi Arabia,Saudi,1
8,6/30/2019,One M9,HTC One M9,HTC,Google,Android,Smartphone,Y,Y,Y,Y,Y,Y,N,Male,26-35,SYR,Syria,Non-Saudi,21
9,6/30/2020,ScanPal EDA50,Honeywell ScanPal EDA50,Honeywell,Google,Android,Smartphone,Y,Y,Y,Y,Y,Y,N,Male,36-55,SAU,Saudi Arabia,Saudi,91

In [27]:
df_dirty.head(10)

,CAL_DT,MODEL_NAME,BRAND_FULL_NAME,VENDOR_NAME,OS_NAME,DEVICE_TYPE,_2G_FLG,_3G_FLG,_4G_FLG,WIFI_FLG,BLUETOOTH_FLG,TOUCH_SCREEN_FLG,DUAL_SIM_FLG,GENDER_TYPE_CD,AGE_B,NATIONALITY_CD,NATIONALITY_NAME,DEVICE_COUNT
0,2019-01-31,O@Ne x9,HTC One. X9@,Google,Android,"SmartpHo,ne",Y,Y,Y#,Y,Y,Y,Y,Male,36@-55,LK@A,Sri Lanka,9
1,2020-05-31_,X2-00,NokiA X2-00,Nokia,PRopri_etarY,MobilE Ph@onE,Y,N,N,N,Y,N@,N,Male,<1 8 @,NaN,NaN,1
2,20 1_9-01 -31,"DesiRe, @626 nFc Dua%l %SIm",HTC DEsIRe 626 NFC Dual# $S%im,Google,Android,SmarTPh one,Y,Y,Y,Y,Y,Y,Y,NaN,26-#35.,SA.U_,Saudi Arabia,1
3,2019-12-31,C7-00,Nokia C7-00,Nokia,"S,y%mbia_n",Smartphone,Y,Y,N,Y,Y,Y,N,Male,18-@2#5,BGD,"Ba$ngla,de$sh",2
4,2019-09-30,1202,Noki#a 1_20.2@,Nokia,Proprietary,Mobile Phone,Y,N,N,N,N,N@,N,NaN,36-55,BGD,Bangladesh,4_
5,2020-04-30,BlAde V7 Lite,ZTE Blade V7 Lite,Google,Android,Smartphone,Y,Y,Y,Y,Y@,Y,Y,Fem Al$e,>55,IDN,Indonesia,1
6,2019-08-31,I6 Metal @O NE,"QmObiLE $i%6% ,Meta,l ONE",goo#gle,AnDr%o@id,Smartp%hoNe,Y,Y,N,Y,Y,Y,Y,Mal@e,36 -55,EGY,E#g#ypT,1
7,2020-0$1-31,SH#F@3_3,au SHF$33,Google,Android,SMartphOne@,Y,Y,Y,Y,Y,Y,N,NaN,NA @,SAU,Saudi Arabia,1
8,201@9-06-30#,On%e M9,H#TC One M9,"G%ooGl,e",An%droi$d,Smartphone,Y,Y,y,Y,Y,Y_,N,Male,26-3_5.,SYR,Syria,21
9,2020-06-30,Sca_n_Pa%l# E#DA50,Ho%ne@yw%e%ll S_canPal EDA50,Google,Androi$d,Smartphone,Y,Y,Y,"Y,",y,Y,N,Male$,3%6-55,SAU,SAu#di A_rab%ia,91

In [35]:
df_dirty.to_csv('handsets_opendata_dirty.csv', index=False)

In [28]:
df_dirty.tail(10)

,CAL_DT,MODEL_NAME,BRAND_FULL_NAME,VENDOR_NAME,OS_NAME,DEVICE_TYPE,_2G_FLG,_3G_FLG,_4G_FLG,WIFI_FLG,BLUETOOTH_FLG,TOUCH_SCREEN_FLG,DUAL_SIM_FLG,GENDER_TYPE_CD,AGE_B,NATIONALITY_CD,NATIONALITY_NAME,DEVICE_COUNT
3150698,2019-09-30,A2$010 #Du#a#l S.i_m,Lenovo A2010 Dual Sim,Google,A.nd_roiD,Smartphone,Y,Y,Y,Y,Y,y,Y,Male,NA%,E GY,Egypt,12#
3150699,2@019_-09-30,"A2010 Du$al, Sim",Lenovo A2010 Dual Sim,Google,A.ndroid_,Smartphone,Y,Y_,Y,Y,Y,Y,Y,NaN,36-55,EG#Y,Egypt,2
3150700,2019-09- 30,A2010 Dual Sim,Lenovo A2010 Dual Sim,Google,"And,roiD",Smartphone,Y,Y,Y,y,Y,Y,Y,male,"NA ,",IND,India,88
3150701,2019-09-30,A2010 Dual Sim,"Lenov_o A2010 D_ual ,Sim",G_oogle,Android,Smartphone,Y,Y,Y,Y,Y,y,Y,MAle,26-35,SYR,Syria,6
3150702,2@0@19-@09-30,"A201,0 .Dual S%i%m",Lenovo A2010 Dual Sim,Google,Android,S#mar_tphOn#e,Y,Y,Y,Y,Y,Y,Y,"Fem,a.l,e$",>55,"PHL,",Philippines,4
3150703,2019-09-30,A2010 Dua%l Si%m,Lenovo A2010 Dual Sim,GooglE,Android,Smartphone,Y,Y,Y,Y.,Y,Y,Y,Female,>5#5,LBY,Libya,1
3150704,2019-09-30,A2010 Dual Sim,Lenovo A2010 Dual Sim,G.o#ogle,"A#NdRo,id",Smartph_one,Y,Y,"Y,",Y,Y,Y,Y,Male,26#-35%,J$O%R,Jordan,2
3150705,2019.-09-30,A2010 Dual Sim,L#Enov.o A2010 Dual $Sim,GooGle,Android,SmaRtp@ho$n.e,Y,Y,Y,Y,Y,Y,Y,Male,NA,NPl,Ne pal,6
3150706,201_9 -09.-30.,A2@010 Dual Sim#,Lenovo A2010 Dual Sim,G@oogl_e,Android,Smartphone,Y,Y,Y,Y,Y,Y,Y,"Mal,E",>55,KWT,Kuwait,1
3150707,2019-09-30,A2010$ dual Sim,L#enoVO A20@10 Dua#l Sim,"GOo,gle",Andr oid,Smartphone,Y,Y,Y%,Y,Y,Y,Y,Male,26-35,EGY,egy%pt,49

In [36]:
df_dirty_sample = df_dirty.sample(n=200_000, random_state=42)
df_dirty_sample.head()

,CAL_DT,MODEL_NAME,BRAND_FULL_NAME,VENDOR_NAME,OS_NAME,DEVICE_TYPE,_2G_FLG,_3G_FLG,_4G_FLG,WIFI_FLG,BLUETOOTH_FLG,TOUCH_SCREEN_FLG,DUAL_SIM_FLG,GENDER_TYPE_CD,AGE_B,NATIONALITY_CD,NATIONALITY_NAME,DEVICE_COUNT
2818415,"2 0.19-.0,7-31",1.x Dual S.im,Alcatel 1x Dual Sim,GooGl#e,Android,Sm$Artp_hOne,y,Y%,Y,Y,Y$,Y,Y,Female,26-35,NaN,NaN,4
1763540,2@019-03-31,K7 Dual# Sim,LG K7 _D#u#al Sim%,Google,Android,Smartphone,Y,Y,N,Y,Y,Y,Y,Female,18-25,JOR,Jo%rdaN,1
1991884,201_9-11-30,EL UG a I3$,paNa%soni.c elUGA I3,Google,Android,SmarTp.hone,Y,Y,n,Y,Y,Y,Y,"Femal,E",>55,ZAF,South Africa,1
1100868,2019-08-31,M9_8@,H_eDy M98,HEDY,P#RoprIetary_,Mobile Phone,Y,N,n,N,y,N,N,Fem.a@lE,36-5%5,YEM_,Yemen,3@
1304841,"20_19-12,-3,1",105,Noki a# 10_5,NoKi%a.,"Prop,rie.taRy",mobile Pho.Ne$,Y,N,N,N,N,N,N,Male,NA,IND,I#ndia,3758

In [37]:
df_dirty_sample.to_csv('handsets_opendata_dirty_1.csv', index=False)